version: '3'
# networks:
#   xxx_project:
#     external: true
volumes:
  vendor:
  node_modules:
services:
  nginx:
    image: nginx:1.14-alpine
    hostname: nginx.com
    ports:
      - '80:80'
      # - '443:443'
    environment:
      - PHP_FPM_CONTAINER=php-fpm
      - PHP_FPM_PORT=9000
      - SRC_DIR_HOST=./${SRC_DIR_HOST}
      - SRC_DIR_CONTAINTER=/var/www/${SRC_DIR_CONTAINTER}
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ${SRC_DIR_HOST}:${SRC_DIR_CONTAINTER}
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php
    working_dir: ${SRC_DIR_CONTAINTER}
    volumes:
      #- ./php/conf.d/my.ini:./php/conf.d/my.ini
      - ${SRC_DIR_HOST}:${SRC_DIR_CONTAINTER}
    #user: 1000:1000
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: docker
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ~/temp/mysql/data:/var/lib/mysql
        - ~/temp/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        - ~/temp/mysql/sql:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - /sessions
