version: '3'
volumes:
  vendor:
  node_modules:
services:
  nginx:
    image: nginx:1.14-alpine
    hostname: nginx.com
    ports:
      - '80:80'
    environment:
      - PHP_FPM_CONTAINER=php-fpm
      - PHP_FPM_PORT=9000
      - SRC_DIR_HOST=./src
      - SRC_DIR_CONTAINTER=/var/www/src
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php
    working_dir: ${SRC_DIR_CONTAINTER}
    volumes:
      - ${SRC_DIR_HOST}:${SRC_DIR_CONTAINTER}
      - ./php/conf.d:/usr/local/etc/php/conf.d
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/temp/mysql/data:/var/lib/mysql
      - ~/temp/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ~/temp/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - /sessions
